### ISSUE TITLE
Why is first image taken like this?

### ISSUE THREAD

**Issue by sumitanilkshirsagar** [meerap1/Automatic-Damage-Detection-in-Construction-Projects#1]
https://github.com/meerap1/Automatic-Damage-Detection-in-Construction-Projects/blob/ec6a73a77ebae5f36c13de9d2f8dc17dc1bd92a0/object_tracking.py#L19

First  image (which initializes the tracker), let it be the image which is extracted from the video at the exact time of damage recorded in json. And its bbox should be taken from the json. bbox should not be taken using cv2.selectROI

**Comment by meerap1** [comment]
I have some doubts in first issue, Some json files like Shimoga don't have bbox details. Also, most of the images are from the exact time of the damage. Should i take one random image with the same time by Distance from railtop(m) value.  or is there any other ides?
![Screenshot 2024-04-04 104514](https://github.com/meerap1/Automatic-Damage-Detection-in-Construction-Projects/assets/156745402/d10822d9-d0b2-4e4e-9ac8-937dade0fc1d)
@sumitanilkshirsagar

**Comment by sumitanilkshirsagar** [comment]
If bbox details are not there , move the files to a different folder called no_bbox. And don't use those for training

**Comment by meerap1** [comment]
We have **Shimoga**, **kr_nagar**, **krs dam**, **shirawata dam**, **sholayar dam** and **vani vilasa**. In this  Shimoga, kr_nagar, shirawata dam don't have bbox details. If we use the other 3 , we will lose some of the damages, Not all the damages are present in all the folders. Is that okay, and could you please tell me som esuggestions on first_image_path = image_files[0]. @sumitanilkshirsagar

**Comment by sumitanilkshirsagar** [comment]
damage_type_ms_ref indicates the time in the video . The frame in video at that time should be taken as the first image.
