### ISSUE TITLE
Get labels fro this

### ISSUE THREAD

**Issue by sumitanilkshirsagar** [meerap1/Automatic-Damage-Detection-in-Construction-Projects#2]
https://github.com/meerap1/Automatic-Damage-Detection-in-Construction-Projects/blob/ec6a73a77ebae5f36c13de9d2f8dc17dc1bd92a0/object_tracking.py#L35

The xy,w,h should be converted into the yolo label.txt corresponding to the image that was just processed.

**Comment by meerap1** [comment]
Solved!
