### ISSUE TITLE
Doubt about window not showing entire image

### ISSUE THREAD

**Issue by sumitanilkshirsagar** [meerap1/Automatic-Damage-Detection-in-Construction-Projects#3]
Try using cv2.namedWindow("Display_Image", cv2.WINDOW_NORMAL)
Then give the same windowname "Display_Image" to selectROI function, imshow function etc
That should resolve the issue.
If not , also add cv2.resizeWindow(window_name, 1280, 720) before and after selectROI and imshow

**Comment by meerap1** [comment]
Solved! @sumitanilkshirsagar
